/**
 * Automatically generated by Zserio C++ extension version 1.0.
 */

#ifndef TUTORIAL_LANGUAGE_H
#define TUTORIAL_LANGUAGE_H

#include <string>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/PreWriteAction.h>
#include <zserio/Types.h>

namespace tutorial
{

class Language
{
public:
    /**
     * The type this enum is based on.
     *
     * This is the C++ mapping of the original zserio type. It can be
     * wider than the original type. E.g. "enum bit:3" would have uint8_t
     * as its base type.
     */
    typedef uint8_t _base_type;

    enum e_Language
    {
        CPP = UINT8_C(0),
        JAVA = UINT8_C(1),
        PYTHON = UINT8_C(2),
        JS = UINT8_C(3)
    };

    Language();
    Language(e_Language value);
    explicit Language(zserio::BitStreamReader& _in);

    operator e_Language() const;
    uint8_t getValue() const;

    size_t bitSizeOf(size_t _bitPosition = 0) const;
    size_t initializeOffsets(size_t _bitPosition = 0) const;

    bool operator==(const Language& other) const;
    bool operator==(e_Language other) const;
    int hashCode() const;

    void read(zserio::BitStreamReader& _in);
    void write(zserio::BitStreamWriter& _out,
            zserio::PreWriteAction _preWriteAction = zserio::ALL_PRE_WRITE_ACTIONS) const;

    const char* toString() const;

    static Language toEnum(uint8_t rawValue);

private:
    e_Language m_value;
};

} // namespace tutorial

#endif // TUTORIAL_LANGUAGE_H
