name: Linux

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Build Zserio C++ tutorial
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Test Zserio C++ tutorial
      run: |
        build/ZserioTutorialCpp write_joe
        build/ZserioTutorialCpp read
        build/ZserioTutorialCpp write_boss
        build/ZserioTutorialCpp read

    - name: Build Zserio C++ tutorial (sources regeneration)
      run: |
        cd build
        rm -rd *
        cmake .. -DCMAKE_BUILD_TYPE=Release -DREGENERATE_CPP_SOURCES=ON
        cmake --build .

    - name: Test Zserio C++ tutorial (sources regeneration)
      run: |
        build/ZserioTutorialCpp write_joe
        build/ZserioTutorialCpp read
        build/ZserioTutorialCpp write_boss
        build/ZserioTutorialCpp read

    - name: Archive Zserio C++ tutorial binary
      uses: actions/upload-artifact@v3
      with:
        name: zserio-tutorial-cpp-${{matrix.os}}
        path: build/ZserioTutorialCpp
