name: Windows

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_windows:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["windows-latest"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Conan v2
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan>=2.0
        conan profile detect
      shell: bash

    - name: Build Zserio C++ tutorial
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Test Zserio C++ tutorial
      run: |
        build/Release/ZserioTutorialCpp write_joe
        build/Release/ZserioTutorialCpp read
        build/Release/ZserioTutorialCpp write_boss
        build/Release/ZserioTutorialCpp read
      shell: bash

    - name: Build Zserio C++ tutorial (sources regeneration)
      run: |
        cd build
        rm -rd *
        cmake .. -DREGENERATE_CPP_SOURCES=ON
        cmake --build . --config Release
      shell: bash

    - name: Test Zserio C++ tutorial (sources regeneration)
      run: |
        build/Release/ZserioTutorialCpp write_joe
        build/Release/ZserioTutorialCpp read
        build/Release/ZserioTutorialCpp write_boss
        build/Release/ZserioTutorialCpp read
      shell: bash

    - name: Build Zserio C++ tutorial for Conan users
      run: |
        conan build ./conan --build=missing --output=build_conan
      shell: bash

    - name: Test Zserio C++ tutorial for Conan users
      run: |
        build_conan/Release/ZserioTutorialCpp write_joe
        build_conan/Release/ZserioTutorialCpp read
        build_conan/Release/ZserioTutorialCpp write_boss
        build_conan/Release/ZserioTutorialCpp read
      shell: bash

    - name: Build Zserio C++ custom memory management tutorial
      run: |
        mkdir build_pmr
        cd build_pmr
        cmake ../pmr
        cmake --build . --config Release
      shell: bash

    - name: Test Zserio C++ custom memory management tutorial
      run: |
        build_pmr/Release/ZserioTutorialCppPmr write_joe
        build_pmr/Release/ZserioTutorialCppPmr read
        build_pmr/Release/ZserioTutorialCppPmr write_boss
        build_pmr/Release/ZserioTutorialCppPmr read
      shell: bash

    - name: Build Zserio C++ custom memory management tutorial (sources regeneration)
      run: |
        cd build_pmr
        rm -rd *
        cmake ../pmr -DREGENERATE_CPP_SOURCES=ON
        cmake --build . --config Release
      shell: bash

    - name: Test Zserio C++ custom memory management tutorial (sources regeneration)
      run: |
        build_pmr/Release/ZserioTutorialCppPmr write_joe
        build_pmr/Release/ZserioTutorialCppPmr read
        build_pmr/Release/ZserioTutorialCppPmr write_boss
        build_pmr/Release/ZserioTutorialCppPmr read
      shell: bash

    - name: Archive Zserio C++ tutorial binary
      uses: actions/upload-artifact@v4
      with:
        name: zserio-tutorial-cpp-${{matrix.os}}
        path: build/Release/ZserioTutorialCpp.exe
